language: java
sudo: required # faster builds
jdk:
  - oraclejdk7
  - openjdk7

before_install:
 - chmod 777 -R .

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)