package views.Main;

import javax.swing.*;
import java.awt.*;

public class MainForm {
    private JPanel jPanelMain;
    private JTabbedPane tabbedPane;

    public MainForm() {
        //this.$$$setupUI$$$();
        initForm();
    }

    private void initForm() {
        jPanelMain = new JPanel();
        jPanelMain.setLayout(new GridBagLayout());
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.weightx = 1.0;
        constraints.weighty = 1.0;
        constraints.fill = GridBagConstraints.BOTH;
        tabbedPane = new JTabbedPane();
        tabbedPane.addTab("Instancia 1", makeTextPaned());
        jPanelMain.add(tabbedPane, constraints);
    }

    private Component makeTextPaned() {
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.BOTH;


        //Left side of the board
        JTextArea jTextAreaMooseOutput = new JTextArea();
        jTextAreaMooseOutput.setEditable(false);
        JScrollPane jScrollPaneLeftSide = new JScrollPane(jTextAreaMooseOutput);

        //Right side of the board
        JPanel jPanelRightSide = new JPanel();
        jPanelRightSide.setLayout(new GridBagLayout());

        constraints.gridy = 0;//First row

        JLabel jLabelMooseExecutable = new JLabel();
        jLabelMooseExecutable.setText("Executable path");
        constraints.weightx=1.0;
        constraints.gridx = 0;
        jPanelRightSide.add(jLabelMooseExecutable, constraints);

        JTextField jTextFieldMooseExecutable = new JTextField();
        jTextFieldMooseExecutable.setText("HOLA MUNDO");
        constraints.gridx = 1;
        jPanelRightSide.add(jTextFieldMooseExecutable, constraints);

        JButton jButtonSearchMooseExecutable = new JButton("Buscar");
        constraints.gridx = 2;
        jPanelRightSide.add(jButtonSearchMooseExecutable, constraints);


        constraints.gridy = 1;//Second row

        JLabel jLabelMooseImage = new JLabel();
        jLabelMooseImage.setText("Image path");
        constraints.weightx = 0.5;
        constraints.gridx = 0;
        jPanelRightSide.add(jLabelMooseImage, constraints);

        JTextField jTextFieldMooseImage = new JTextField();
        constraints.gridx = 1;
        jPanelRightSide.add(jTextFieldMooseImage, constraints);

        JButton jButtonSearchMooseImage = new JButton("Buscar");
        constraints.gridx = 2;
        jPanelRightSide.add(jButtonSearchMooseImage, constraints);


        constraints.gridy = 2;//Third row

        constraints.weightx=1.0;
        constraints.weighty=1.0;
        JTextArea jTextAreaSuggestions = new JTextArea();
        jTextAreaSuggestions.setEditable(false);
        JScrollPane jScrollPaneJLabelSuggestions = new JScrollPane(jTextAreaSuggestions);
        constraints.weightx  = 0.0;
        constraints.gridx = 0;
        constraints.gridwidth=3;//# of columns to fill
        constraints.ipady = 200;
        jPanelRightSide.add(jScrollPaneJLabelSuggestions,constraints);

        constraints.gridy = 3;//Fourth row

        JButton jButtonRunStop = new JButton("Run - Stop");
        constraints.ipady = 0;
        constraints.gridx= 1;
        constraints.gridwidth=-3;
        constraints.weightx  = 0.5;
        constraints.weighty=0.0;
        jPanelRightSide.add(jButtonRunStop,constraints);

        JButton jButtonDelete = new JButton("Delete");
        constraints.ipady = 0;
        constraints.gridx= 2;
        jPanelRightSide.add(jButtonDelete,constraints);


        //Grouping all components
        JSplitPane jSplitPane = new JSplitPane(
                JSplitPane.HORIZONTAL_SPLIT,
                jScrollPaneLeftSide,
                jPanelRightSide
        );
        jSplitPane.setDividerLocation(300);
        constraints.weightx=1.0;
        constraints.weighty=1.0;

        //Add JSplitPane to final mainPanel
        mainPanel.add(jSplitPane,constraints);
        return mainPanel;
    }

    public JPanel getjPanelMain() {
        return jPanelMain;
    }

    public void setjPanelMain(JPanel jPanelMain) {
        this.jPanelMain = jPanelMain;
    }

    public void addController () {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanelMain = new JPanel();
        jPanelMain.setLayout(new GridBagLayout());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanelMain;
    }
}
