package views.LanguageChooser;

import abstracts.MVC.Controller;

import javax.swing.*;
import java.awt.*;

public class LanguageChooserForm {
    private JList jListLanguages;
    private JPanel jPanelMain;
    private JButton jButtonAccept;
    private JButton jButtonCancel;

    public static final String J_BUTTON_ACCEPT_COMMAND = "LanguageChooserForm.jButtonAccept";
    public static final String J_BUTTON_CANCEL_COMMAND = "LanguageChooserForm.jButtonCancel";

    public LanguageChooserForm() {
        initForm();
        jButtonAccept.setActionCommand(J_BUTTON_ACCEPT_COMMAND);
        jButtonCancel.setActionCommand(J_BUTTON_CANCEL_COMMAND);
    }

    private void initForm() {
        jPanelMain = new JPanel();
        jPanelMain.setLayout(new GridBagLayout());
        jPanelMain.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        GridBagConstraints c = new GridBagConstraints();

        jListLanguages = new JList<>();
        //jListLanguages.setBorder(BorderFactory.createEmptyBorder(10,0,10,0));
        //jListLanguages.add(Box.createRigidArea(new Dimension(0,5)));
        c.fill = GridBagConstraints.HORIZONTAL;
        c.ipady = 50;
        c.gridwidth = 2;
        c.gridx = 0;
        c.gridy = 0;
        jPanelMain.add(jListLanguages, c);

        //Reset to default for next gui components
        c.ipady = 0;
        c.gridwidth = 1;
        c.fill = GridBagConstraints.NONE;

        jButtonAccept = new JButton();
        jButtonAccept.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        c.gridx = 0;
        c.gridy = 1;
        jPanelMain.add(jButtonAccept, c);

        jButtonCancel = new JButton();
        jButtonCancel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        //c.weightx=0.5;
        c.gridx = 1;
        c.gridy = 1;
        jPanelMain.add(jButtonCancel, c);
    }

    public JPanel getJPanelMain() {
        return jPanelMain;
    }

    public void setJPanelMain(JPanel jPanelMain) {
        this.jPanelMain = jPanelMain;
    }

    public JList getJListLanguages() {
        return jListLanguages;
    }

    public void setJListLanguages(JList jListLanguages) {
        this.jListLanguages = jListLanguages;
    }

    public JButton getJButtonAccept() {
        return jButtonAccept;
    }

    public void setJButtonAccept(JButton jButtonAccept) {
        this.jButtonAccept = jButtonAccept;
    }

    public JButton getJButtonCancel() {
        return jButtonCancel;
    }

    public void setJButtonCancel(JButton jButtonCancel) {
        this.jButtonCancel = jButtonCancel;
    }

    public void addController(Controller controller) {
        jButtonAccept.addActionListener(controller);
        jButtonCancel.addActionListener(controller);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanelMain = new JPanel();
        jPanelMain.setLayout(new GridBagLayout());
        jButtonAccept = new JButton();
        jButtonAccept.setText("Ok");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        jPanelMain.add(jButtonAccept, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        jPanelMain.add(scrollPane1, gbc);
        jListLanguages = new JList();
        jListLanguages.setSelectionMode(0);
        scrollPane1.setViewportView(jListLanguages);
        jButtonCancel = new JButton();
        jButtonCancel.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        jPanelMain.add(jButtonCancel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanelMain;
    }
}
